; Generated by AutoGui, MemoryUpdater:2.5.8
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui, MemoryUpdater:Font, s11 Bold
Gui, MemoryUpdater:Add, GroupBox, x9 y5 w343 h170, Imports
Gui, MemoryUpdater:Font
Gui, MemoryUpdater:Add, DropDownList, x17 y48 w165 vImportsDrowndownList, ||
Gui, MemoryUpdater:Add, Button, x192 y48 w30 h21 gUpdater_Add_To_Imports, +
Gui, MemoryUpdater:Add, Button, x+5 y48 w30 h21 vUpdater_Remove_Imports gUpdater_Remove_From_List, -
Gui, MemoryUpdater:Add, Button, x+5 y48 w80 h21 gUpdater_Check_Imports, Check
Gui, MemoryUpdater:Add, Text, x18 y+20 w235 h32 +0x200 vImportUpdatesAvailable,
Gui, MemoryUpdater:Add, Button, x262 yp+0 w80 h21 gUpdater_Download_Imports, Download

Gui, MemoryUpdater:Font, s11 Bold
Gui, MemoryUpdater:Add, GroupBox, x362 y5 w343 h170, Pointers
Gui, MemoryUpdater:Font
Gui, MemoryUpdater:Add, Text, x374 y30 w120 h21, Pointer Database
Gui, MemoryUpdater:Add, DropDownList, x373 y48 w165 vPointerDBDrowndownList, ||
Gui, MemoryUpdater:Add, Button, x547 y48 w30 h21 gUpdater_Add_To_Pointers, +
Gui, MemoryUpdater:Add, Button, x+5 y49 w30 h21 vUpdater_Remove_PointerDB gUpdater_Remove_From_List, -
Gui, MemoryUpdater:Add, Button, x+5 y49 w80 h21 gUpdater_Check_PointerDB, Check
Gui, MemoryUpdater:Add, Text, x376 y80 w121 h21, Specific Pointer
Gui, MemoryUpdater:Add, DropDownList, x373 y98 w165 vCurrentPointersDrowndownList, ||
Gui, MemoryUpdater:Add, Button, x547 y98 w30 h21 gUpdater_Add_To_CurrentPointer, +
Gui, MemoryUpdater:Add, Button, x+5 y98 w30 h21 vUpdater_Remove_CurrentPointer gUpdater_Remove_From_List, -
Gui, MemoryUpdater:Add, Button, x+5 y98 w80 h21 gUpdater_Check_CurrentPointer, Check
Gui, MemoryUpdater:Add, Text, x373 y+5 w235 h42 +0x200 vPointersUpdatesAvailable,
Gui, MemoryUpdater:Add, Button, x620 yp+15 w80 h21 gUpdater_Download_Pointer, Download


Gui, MemoryUpdater:Add, Progress, x8 y187 w575 h21 +0x800000 vUpdater_Download_Progress_Bar cBackgroundDefault, 100 ; [_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _]
Gui, MemoryUpdater:Font, c0xCCCCCC s9 Normal, Verdana					; FontSize s9 and color dark grey (606060)
Gui, MemoryUpdater:Add, Text, x18 y189 w563 +Right vUpdater_Download_Progress_Text BackgroundTrans, Done!
Gui, MemoryUpdater:Add, Button, x587 y187 w121 h21 gUpdater_Exit, Done

#include %A_LineFile%\..\IC_MemoryUpdater_Functions.ahk

Gui,+Resize
Gui, MemoryUpdater:Show,, MemoryRead Updater

Updater_Check_Imports()
{
    Gui, MemoryUpdater:Submit, NoHide
    global ImportsDrowndownList
    g_MemUpdater.ResetDownloadProgressBar()
    g_MemUpdater.CheckImportsForUpdate(g_MemUpdater.ImportsURLs[ImportsDrowndownList])
    ; if newer, download all import files using github api to find them
}

Updater_Check_PointerDB()
{
    GuiControl, MemoryUpdater:+0x200, PointersUpdatesAvailable,
    Gui, MemoryUpdater:Submit, NoHide
    global PointerDBDrowndownList
    g_MemUpdater.ResetDownloadProgressBar()
    localFileLoc := A_LineFile . "\..\..\..\SharedFunctions\PointerData.json"
    url := g_MemUpdater.PointerDBURLs[PointerDBDrowndownList]
    g_MemUpdater.CheckPointerForUpdate(localFileLoc, url)
}

Updater_Check_CurrentPointer()
{
    GuiControl, MemoryUpdater:+0x200, PointersUpdatesAvailable,
    Gui, MemoryUpdater:Submit, NoHide
    global CurrentPointersDrowndownList
    g_MemUpdater.ResetDownloadProgressBar()
    localFileLoc := A_LineFile . "\..\..\..\SharedFunctions\MemoryRead\CurrentPointers.json"
    url := g_MemUpdater.CurrentPointersURLs[CurrentPointersDrowndownList]
    g_MemUpdater.CheckPointerForUpdate(localFileLoc, url)
}

Updater_Download_Pointer()
{
    g_MemUpdater.DownloadPointer()
}

Updater_Download_Imports()
{
    Gui, MemoryUpdater:Submit, NoHide
    global ImportsDrowndownList
    g_MemUpdater.DownloadImports(ImportsDrowndownList)
}

Updater_Add_To_Imports()
{
    g_MemUpdater.PromptForURL("Imports folder", "ImportsURLs")
}

Updater_Add_To_Pointers()
{
    g_MemUpdater.PromptForURL("Pointers Database", "PointerDBUrls")
}

Updater_Add_To_CurrentPointer()
{
    g_MemUpdater.PromptForURL("Current Pointer File", "CurrentPointersURLs")
}

Updater_Remove_From_List()
{
    g_MemUpdater.RemoveURLFromList()
}

Updater_Exit()
{
    MsgBox, 4,Closing Updater..., Restart Script Hub?
    IfMsgBox, Yes
    {
        ; TODO: close script hub if it's open
        scriptHubLoc := A_LineFile . "\..\..\..\ICScriptHub.ahk"
        Run, %scriptHubLoc%
    }
    ExitApp
}

MemoryUpdaterGuiClose()
{
    Updater_Exit()
}


